defaults_go: &DEFAULTS_GO
  language: go
  go: "1.11"
  cache:
    directories:
      - vendor

defaults_js: &DEFAULTS_JS
  language: node_js
  node_js: "8"
  # install defaults to "npm install", which is done via make
  install: []
  cache:
    directories:
      - ui/node_modules

env:
  global:
    - secure: "TTJvEAPR9emq472XCxLE1KIAfAjeGQrYQskw/Y5Bgo+fyRcI1Jt0+3OerCwtuHpXJPEu2bb9XFmKpp1sByV9l8zUmDaPAE20yN62g2c3+CGAbtoXOdu+ZDwGwixzfH1zOv7Hpd9ICW/KiAXk1d279ch3aUQPSVOAgu63e33pXzxYOplLcEIZtV6ATIFhYYfTJLgMpIo6LH/RHZQlGAIEbvZSRmFfjb3EMB7oKRogSjHZ8+JPYizV7CozW9PrbY2M1iGouTnO7If4TQFmBNuurqJJXidKlrckzGUBpDnD2N/5uyneKdBge1Xl5WSHPYV6bW4gsZC/ecHAVm0Oy5I+rjn5vdDgLNXd8XF6zm90b+LjXiFp9M9y1YPygSqPuYGBllNkNMiDrR2Ho7sTVe8eID4+V7Ksw7g9bI+ehESovqK0STheOiD5KsxtkurvfnLO7yb+XpgZozDwQp0FuYfbZBKdqBOEI55aCOs+9FLaCZru6aKNCT7t0qG11TVTV8chMSlhcON9VI7/L7JXXenFHmp7cakxrs2N9TpJUkajmjgUY3Ia0l5LAcCNQFrFTxqx3i58X1R5bZGeYX7jniybPQf5ZkZay99AhPx5u56AHIFy7zp9ipHwHtSkP/yRPJdjGrR67qR6O+oVYCIalXSQFVGGWYO2R2K/IymZIcYwARk="

jobs:
  include:
    - stage: Greenkeeper
      # this stage only runs for branches with name starting with "greenkeeper"
      # it only needs to run as part of a PR send by Greenkeeper bot, it doesn't
      # do anything for other branches or PRs
      if: branch =~ /^greenkeeper.*/
      <<: *DEFAULTS_JS
      script:
        - make greenkeeper-lockfile

    - stage: Test Go code
      <<: *DEFAULTS_GO
      before_script:
        - make mock-assets
      script: make test-go
      after_success:
        - bash <(curl -s https://codecov.io/bash) -F backend

    - stage: Test JavaScript code
      <<: *DEFAULTS_JS
      env:
        - NODE_ENV=test
      script: make test-js
      after_success:
        - bash <(curl -s https://codecov.io/bash) -F ui -s ui

    - stage: Lint Go code
      <<: *DEFAULTS_GO
      before_script:
        - make mock-assets
      script: make lint-go

    - stage: Lint JavaScript code
      <<: *DEFAULTS_JS
      script: make lint-js

    - stage: Lint docs
      <<: *DEFAULTS_JS
      script: make lint-docs

    - stage: Build Docker image
      language: generic
      sudo: true
      addons:
        apt:
          packages:
            - docker-ce
      script: make docker-image

    - stage: Build and Deploy
      <<: *DEFAULTS_GO
      cache:
        # disable cache so we always build from scratch
        directories: []
      before_script:
        # this stage needs to build everything including assets file and that
        # requires running webpack, so we need nodejs here
        - nvm install 8
      script:
        # compile assets via webpack and build those into bindata_assetfs.go file
        - make bindata_assetfs.go
        # verify that there are no uncommited changes from (re)compiling sass
        # assets
        - git diff --exit-code
        # install bakelite, we can't "go get" a tag from github, so we fetch the binary
        - export BAKELITE_VERSION="v0.1.0"
        - export BAKELITE_OS=$(go env GOHOSTOS)
        - export BAKELITE_ARCH="$(go env GOHOSTARCH)"
        - curl -L -o bakelite.tar.gz "https://github.com/terinjokes/bakelite/releases/download/${BAKELITE_VERSION}/bakelite-${BAKELITE_OS}-${BAKELITE_ARCH}.tar.gz"
        - tar -xf bakelite.tar.gz
        # and now compile using bakelite for all target archs
        - export SOURCE_DATE_EPOCH=$(git show -s --format=%ci ${TRAVIS_TAG:-${TRAVIS_COMMIT}}^{commit})
        - ./bakelite-${BAKELITE_OS}-${BAKELITE_ARCH} -platforms="-plan9" -ldflags="-X main.version=\"$(make show-version)\"" github.com/prymitive/unsee
        - for i in unsee-*; do tar --mtime="${SOURCE_DATE_EPOCH}" --owner=0 --group=0 --numeric-owner -c $i | gzip -n - > $i.tar.gz; done
        - shasum -a 512 unsee-*.tar.gz | tee sha512sum.txt
      deploy:
        provider: releases
        api_key:
          secure: P0xobtDkFWfzTm6UF2OTrXicmzykk7Tnm9p3gb70DORlkbGzM+/kVNe0aYWcZrubbSi2Ld41EWifDGKOgqFi8GZYULaXanMbGHX82rElMLryhUaagXmgS1adlwhsT6Dc9bBkJnQ7ezRy5hvuzli+rXoeLO3uE8aRpf05s+CDMyVneE/vURvAxfiuMiIL+aI1Le54N8vHENaxmP8xRt9NwKt2D+fErF3isSLdS6tkW7BrsImVKIjebvG+bUnZyVjvGHokBlQFRD2W8M87frkLDYmsK2w9DCpNiyUGYQoKqqQKysswTexfrlObyGadMgb3G7BQM/8v+jlag7b/4v+EJ2AIppSXzeY1Jj8IrKqkscGihmgbJABhKp5A8VgnoCiGm5mXPuhp7A7gFtuLpR3FWpx1Xe7hbVw6bjmDRoYyRasZ0uCcsWPy/nShWFyahKSzaxdNQs1aGAWgVD6t+/EvGG5+tl1ThUm9+uw7E8FIiKe9M2mGiu5JK5mBSN4Drw4+wz+s2IfiLF3I/UVZqD7PBetHW1uv2hnlth7sIjsCkPCC/Myis99zjiR3C74rdxr99/ux/BKjH44Fm1HL2qakUcbytE0YaMppebHm35oB1kBX5RBFjXGZYtkvS+BTpUncl1IEXxuaorA8nNEv3fqH/UgpzmKIqiaryPehezYYFCI=
        skip_cleanup: true
        file_glob: true
        file:
          - unsee-*.tar.gz
          - sha512sum.txt
        on:
          repo: prymitive/unsee
          tags: true
